### PR TITLE
Add compose file and allow debug on tracing

### PR DESCRIPTION
**Pull request by aocenas**
Due to some issues I had with running this through k8s and ksonnet I created a docker-compose file with setup needed to run this with Loki logging and Jaeger running outside (in Grafana/devenv setup). Main motivation is to have this available for testing new tracing functionality in Grafana (links to traces in logs atm).

Not sure if it make sense to have separate way to run this but I think for more people it will be easier to setup and play with it in a docker-compose than with k8s and ksonnet.

### CODE REVIEW

**Comment by aocenas** [comment]
Yeah tbh this is pretty stale too, so not sure if it makes sense to try to merge or not. Don't have that much time to investigate right now and I don't even remember what the problem was that I needed debugging for. So I am ok closing this, it isn't like this could not be reopened or rewritten if needed.

**Comment by jdbaldry** [comment]
Sure that makes sense. I'll close this but keep in mind in case anyone wants it in the future :)

**Comment by tomwilkie** [comment]
:-( some of those code changes looked useful - I really want to be able to see trace ids on log lines.  

@jdbaldry can you resurrect just to go changes?

**Comment by jdbaldry** [comment]
Forgive me if I'm misunderstanding but we as far as I can tell there are already traceIDs for each of the deployments in the tns namespace, though the app and db dwarf the loadgen trace logs. If I understand the PR correctly it is configuring the [jaeger logging reporter](https://www.jaegertracing.io/docs/1.17/troubleshooting/#use-the-logging-reporter) to log spans which can be useful in debugging.

**Comment by aocenas** [comment]
> If I understand the PR correctly it is configuring the jaeger logging reporter to log spans which can be useful in debugging.

Yes exactly it basically just logs `Sent span with ID "foobar"`. I think I needed it just because wasn't seeing any traces in jaeger and just wanted to make sure it is sending them.

**Pull request closed without merging**
