### PR TITLE
Format Jsonnet and lint in CI

### PR DESCRIPTION
**Pull request by jdbaldry**
There looks to be some opinionated human formatting in place that won't get fixed by jsonnetfmt but I've left that for now.

### CODE REVIEW

**Comment by jdbaldry** [comment]
The "Lint Jsonnet" step is failing because the default image for jobs is just a Go image.

I've seen multiple images used through our various projects but a usable image is defined in [cortex-jsonnet](https://github.com/grafana/cortex-jsonnet). Is it fine to re-use that image, should I build a repo specific image, or should I be looking elsewhere?

I've also limited experience with CircleCI, would it be right to split the `lint` job into two `lint-<thing>` jobs in order to use different images?

**Comment by jdbaldry** [comment]
I've borrowed the cortex-jsonnet image for now so that everything passes. Happy to change that if something else is preferred.

**Comment by tomwilkie** [comment]
> borrowed the cortex-jsonnet image

I prefer not to, its easy to just copy in these instances - otherwise we'll end up going down the uber-linter-image path, and there be dragons.  So bring over the dockerfile for cortex-jsonnet and make a new docker repo for this.

Otherwise LGTM

**Comment by jdbaldry** [comment]
Added the Dockerfile and build configuration for a repository specific lint image grafana/tns-lint so now there's no borrowing from cortex-jsonnet :)

**Pull request merged**
